mode: immediate
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}, Nhân đẹp trai vaicalon'
gitSafeReplacementChar: '-'
autoCloseIssue: true
autoLinkIssue: true
autoDeleteBranch: true