mode: immediate
autoLinkIssue: true
silent: false
branchName: '${issue.number}-${issue.title}'
gitSafeReplacementChar: '-'
autoLinkIssue: true
autoCloseIssue: true
branches:
  - label: "type: feature 🔨"
    prefix: feat/
  - label: "type: bug 🐛"
    prefix: fix/
  - label: "type: chore 🧺"
    prefix: chore/
  - label: "type: documentation ✏️"
    prefix: docs/
  - label: "*"
    prefix: issue/