mode: immediate
autoLinkIssue: true
branchName: ${issue.number}-${issue.title}  
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}, Nhân đẹp trai vaicalon'
gitSafeReplacementChar: '-'
autoLinkIssue: true
autoCloseIssue: true
branches:
  - label: "type: feature 🔨"
    prefix: feat/
  - label: "type: bug 🐛"
    prefix: fix/
  - label: "type: chore 🧺"
    prefix: chore/
  - label: "type: documentation ✏️"
    prefix: docs/
  - label: "*"
    prefix: issue/