name: Add Label

on:
  issues:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  add-label:
    name: Add Label

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: okineadev/add-labels@v1.0.5
        with:
          labels: documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}