name: Auto Branch
on:
  issues:
    types: [opened, reopened]
jobs:
  create-issue-branch:
    name: "create issue branch"
    runs-on: ubuntu-latest
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@main
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
