name: Auto Create Branch for Issue

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create branch for issue
        uses: peter-evans/create-branch@v4
        with:
          branch: issue-${{github.event.issue.number}}-${{github.event.issue.title}}
          base: main
